From iteration 7 - `cast` field with relation to `Celebrity` model
ironhack-labs/lab-mongoose-movies pull request #1607
Opened 2021-05-15 07:05 UTC by abernier

Having that relation makes the lab really more interesting.

2021-05-17 13:58 UTC, ross-u requested changes
Overall looking good. One thing that I noticed should be changed before the merge is that some of the references to the models start with a lowercase letter, but should instead start with an uppercase letter

2021-05-17 13:58 UTC, ross-u commented on README.md
> +The `movie` model should have:
Reference to the model name is in lowercase.

2021-05-17 13:58 UTC, ross-u commented on README.md
> +Go back and review what you did to create the `celebrity` model.  You'll need to create a file for the model, and in that file, you'll need to create a schema for the model as well. Don't forget, you
Reference to the model name is in lowercase.

2021-05-17 13:58 UTC, ross-u commented on README.md
> +Go back and review how you did this for the `celebrity` model.  You'll need to:
References to the models starts with a lowercase letter

2021-05-17 14:52 UTC, abernier commented
> Overall looking good. One thing that I noticed should be changed before the merge is that some of the references to the models start with a lowercase letter, but should instead start with an uppercase letter

Hey Uros, I've validated all your 3 xhanges-requests ;) thx

2021-05-18 12:57 UTC, abernier commented
@ross-u sorry, I guessed marking your request-changes as resolved would have done the commit: here it is now https://github.com/ironhack-labs/lab-mongoose-movies/pull/1607/commits/312e2288b0dce19c57190a2f28fd2185f764ec42 :)

We should be good

2021-05-19 20:40 UTC, merged